from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 620)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 620))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 620))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ui_imgs/icons/目标检测.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 100, 621, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 611, 481))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_show = QtWidgets.QLabel(self.frame_2)
        self.label_show.setGeometry(QtCore.QRect(0, 0, 600, 480))
        self.label_show.setMinimumSize(QtCore.QSize(600, 480))
        self.label_show.setMaximumSize(QtCore.QSize(600, 480))
        self.label_show.setStyleSheet("border-image: url(:/icons/ui_imgs/huoyan.png);")
        self.label_show.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_show.setText("")
        self.label_show.setObjectName("label_show")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(630, 100, 451, 481))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox.setGeometry(QtCore.QRect(0, 70, 451, 171))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.PiclineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.PiclineEdit.setGeometry(QtCore.QRect(80, 40, 331, 31))
        self.PiclineEdit.setInputMask("")
        self.PiclineEdit.setReadOnly(True)
        self.PiclineEdit.setPlaceholderText("")
        self.PiclineEdit.setObjectName("PiclineEdit")
        self.VideolineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.VideolineEdit.setGeometry(QtCore.QRect(80, 80, 331, 31))
        self.VideolineEdit.setReadOnly(True)
        self.VideolineEdit.setPlaceholderText("")
        self.VideolineEdit.setObjectName("VideolineEdit")
        self.CapBtn = QtWidgets.QPushButton(self.groupBox)
        self.CapBtn.setGeometry(QtCore.QRect(40, 120, 30, 30))
        self.CapBtn.setStyleSheet("border-image: url(:/icons/icon/camera.png)")
        self.CapBtn.setText("")
        self.CapBtn.setObjectName("CapBtn")
        self.PicBtn = QtWidgets.QPushButton(self.groupBox)
        self.PicBtn.setGeometry(QtCore.QRect(40, 40, 30, 30))
        self.PicBtn.setStyleSheet("border-image: url(:/icons/icon/img.png)")
        self.PicBtn.setText("")
        self.PicBtn.setIconSize(QtCore.QSize(30, 30))
        self.PicBtn.setObjectName("PicBtn")
        self.VideoBtn = QtWidgets.QPushButton(self.groupBox)
        self.VideoBtn.setGeometry(QtCore.QRect(40, 80, 30, 30))
        self.VideoBtn.setStyleSheet("border-image: url(:/icons/icon/video.png)")
        self.VideoBtn.setText("")
        self.VideoBtn.setObjectName("VideoBtn")
        self.CaplineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.CaplineEdit.setGeometry(QtCore.QRect(80, 120, 331, 31))
        self.CaplineEdit.setReadOnly(True)
        self.CaplineEdit.setPlaceholderText("")
        self.CaplineEdit.setObjectName("CaplineEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 260, 451, 221))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 431, 181))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(72)
        self.label_welcome = QtWidgets.QLabel(self.frame_4)
        self.label_welcome.setGeometry(QtCore.QRect(30, 10, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_welcome.setFont(font)
        self.label_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.UserBtn = QtWidgets.QPushButton(self.frame_4)
        self.UserBtn.setGeometry(QtCore.QRect(340, 20, 30, 30))
        self.UserBtn.setStyleSheet("border-image: url(:/icons/icon/user.png)")
        self.UserBtn.setText("")
        self.UserBtn.setIconSize(QtCore.QSize(30, 30))
        self.UserBtn.setObjectName("UserBtn")
        self.ExitBtn = QtWidgets.QPushButton(self.frame_4)
        self.ExitBtn.setGeometry(QtCore.QRect(380, 20, 30, 30))
        self.ExitBtn.setStyleSheet("border-image: url(:/icons/icon/exit.png)")
        self.ExitBtn.setText("")
        self.ExitBtn.setIconSize(QtCore.QSize(30, 30))
        self.ExitBtn.setObjectName("ExitBtn")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 1231, 91))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 1091, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 311, 21))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(1070, 60, 131, 21))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Object Detection System"))
        self.groupBox.setTitle(_translate("MainWindow", "文件导入"))
        self.PiclineEdit.setText(_translate("MainWindow", "请选择图片文件"))
        self.VideolineEdit.setText(_translate("MainWindow", "请选择视频文件"))
        self.CaplineEdit.setText(_translate("MainWindow", "摄像头未开启"))
        self.groupBox_3.setTitle(_translate("MainWindow", "检测结果与位置信息"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "路径"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "编号"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "类别"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "置信度"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "位置"))
        self.label_welcome.setText(_translate("MainWindow", "Welcome, admin!"))
        self.label_3.setText(_translate("MainWindow", "Object Detection System"))
from . import ui_sources_rc
